### ISSUE TITLE
Restrict access to individual users

### ISSUE THREAD

**Issue by xuanxu** [openjournals/buffy#31]
Allow declaring a team in the config file made of individual users:
```yml
teams:
   - editors: 9111824115
   - eics: openjournals/eics
   - testers:
      - xuanxu
      - arfon
      - botsci

```

This option does not query for teams -> no need for admin privileges granted to the bot
