### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by agahkarakuzu** [openjournals/buffy#89]
First of all, thank you so much for putting together a great documentation, it helps me a lot in adapting `buffy` for NeuroLibre tasks!

Regarding the `complete example` for [docs/responders/github_action](https://buffy.readthedocs.io/en/latest/responders/github_action.html),  it would be really useful to replace it with an example from the actual code, e.g.:

```yaml
    github_action:
      - draft_paper:
          command: generate pdf
          workflow_repo: openjournals/joss-papers
          workflow_name: draft-paper.yml
          workflow_ref: master
          description: Generates the pdf paper
          data_from_issue:
            - branch
            - target-repository
            - issue_id
          mapping:
            repository_url: target-repository
  ```

and mentioning that this example is from [this config](https://github.com/openjournals/buffy/blob/joss/config/settings-production.yml) that lives under the `joss` branch of buffy. 

Having a concrete example would ease understanding the origin and destination of the request, as well as its flow throughout the system. Visualizing it mentally can be tricky since it involves a chain of requests. I was quite puzzled till I realized that buffy was deployed to heroku from the `joss` branch :) 

I am happy to send a PR if you think that this is useful.
